// RUN: python3 %vc4_repo_root/compiler/test/Conversion/VC4ValueToVC4Kernel/Support/audit_phase11_strided_ranked_memory.py --repo-root %vc4_repo_root | FileCheck %s

// CHECK: PHASE11_STRIDED_RANKED_SOURCE_AUDIT=PASS
// CHECK: VALUE_STRIDED_RANKED_ADDRESS_PLANNER=YES
// CHECK: PHASE10_MASK_CLASSIFIER_REUSED=YES
// CHECK: GATHER_LANE_STRIDE_STAGED=YES
// CHECK: HIDDEN_MEMREF_DESCRIPTOR_REJECTED=YES
// CHECK: RANK2_TILE_VECTOR_ACCEPTANCE=NO
