// RUN: python3 %vc4_repo_root/compiler/test/Conversion/VC4ValueToVC4Kernel/Support/audit_phase13_value_gemv_static.py --repo-root %vc4_repo_root | FileCheck %s

// CHECK: PHASE13_VALUE_GEMV_SOURCE_AUDIT=PASS
// CHECK: NO_NEW_TARGET_DOT_OP=YES
// CHECK: F32_DOT_USES_FINITE_TREE_POLICY=YES
// CHECK: VECTOR_CONTRACT_STAGED=YES
// CHECK: TT_DOT_STAGED=YES
// CHECK: MULTIBLOCK_K_ACCUMULATION_STAGED=YES
// CHECK: NO_FIXTURE_NAME_SPECIAL_CASES=YES
// CHECK: NO_HIDDEN_EXACT_F32_DOT_CLAIM=YES
// CHECK: F32_DOT_COMPOSITE_EXISTING_MUL_REDUCTION_STORE=YES
// CHECK: READY_FOR_TRITON=NO
