// RUN: python3 %vc4_repo_root/compiler/test/Conversion/VC4ValueToVC4Kernel/Support/audit_phase15_value_sfu_softmax_static.py --repo-root %vc4_repo_root | FileCheck %s

// CHECK: VALUE_SFU_SOFTMAX_SOURCE_AUDIT=PASS
// CHECK: APPROX_MATH_THROUGH_CENTRAL_POLICY_HELPER=YES
// CHECK: EXACT_DEFAULT_MATH_REJECTED=YES
// CHECK: FINITE_MAX_REDUCTION_CENTRAL=YES
// CHECK: SOFTMAX_IS_COMPOSITE_NO_VALUE_OP=YES
// CHECK: NO_FIXTURE_NAME_OR_PATH_SPECIAL_CASES=YES
// CHECK: NO_HIDDEN_EXACT_MATH_CLAIMS=YES
// CHECK: MULTIBLOCK_SOFTMAX_NOT_ACCEPTED=YES
// CHECK: READY_FOR_TRITON=NO
