// RUN: python3 %vc4_repo_root/compiler/test/Conversion/VC4ValueToVC4Kernel/Support/audit_phase17_value_online_softmax_static.py --repo-root %vc4_repo_root | FileCheck %s

// CHECK: VALUE_ONLINE_SOFTMAX_SOURCE_AUDIT=PASS
// CHECK: ONLINE_SOFTMAX_STANDARD_VALUE_COMPOSITE=YES
// CHECK: NO_NEW_VC4VALUE_ONLINE_SOFTMAX_OP=YES
// CHECK: NO_SCALAR_MEMREF_LOAD_SUPPORT_INTRODUCED=YES
// CHECK: NONTRANSPOSED_V_GATHER_REMAINS_STAGED=YES
// CHECK: NATURAL_EXP_SOFTMAX_SEMANTICS_PRESERVED=YES
// CHECK: ONLINE_SOFTMAX_METADATA_USED_FOR_LOWERING=NO
// CHECK: NO_SOURCE_NAME_PATH_FIXTURE_SPECIAL_CASES=YES
// CHECK: QK_SCORE_GENERATION_REMAINS_STAGED=YES
// CHECK: DOT_CONTRACT_REMAINS_STAGED=YES
// CHECK: READY_FOR_TRITON=NO
