// RUN: FileCheck %s --input-file=%vc4_repo_root/compiler/docs/vc4_value_to_vc4kernel_planning.md

// CHECK: PHASE16_VALUE_ATTENTION_APPLY_V0_CONTRACT=LOCKED
// CHECK: VALUE_ATTENTION_APPLY_V0_COMPOSITE_LOWERS_PLANNED=YES
// CHECK: VALUE_ATTENTION_APPLY_V0_SCALED_STATIC_PLANNED=YES
// CHECK: VALUE_ATTENTION_APPLY_V0_F16_STORAGE_STATIC_PLANNED=YES
// CHECK: VALUE_ATTENTION_APPLY_V0_SCALAR_GLOBAL_LOAD_STAGED=YES
// CHECK: VALUE_ATTENTION_APPLY_V0_NONTRANSPOSED_V_GATHER_STAGED=YES
// CHECK: VALUE_ATTENTION_APPLY_V0_K_ZERO_STAGED_OR_GUARD_REQUIRED=YES
// CHECK: READY_FOR_PHASE16_4_VALUE_ATTENTION_APPLY_STATIC=YES
// CHECK: READY_FOR_TRITON=NO
