// RUN: python3 %vc4_repo_root/compiler/test/Conversion/VC4ValueToVC4Kernel/Support/audit_phase16_value_attention_apply_static.py --repo-root %vc4_repo_root | FileCheck %s

// CHECK: VALUE_ATTENTION_APPLY_SOURCE_AUDIT=PASS
// CHECK: ATTENTION_APPLY_METADATA_POLICY_ONLY=YES
// CHECK: ATTENTION_APPLY_METADATA_USED_FOR_LOWERING=NO
// CHECK: STRUCTURAL_ATTENTION_APPLY_TESTS_REQUIRED=YES
// CHECK: MAGIC_METADATA_NOT_COUNTED_AS_EXECUTABLE_SUPPORT=YES
// CHECK: ATTENTION_APPLY_STANDARD_VALUE_COMPOSITE=YES
// CHECK: NO_NEW_VC4VALUE_ATTENTION_OP=YES
// CHECK: NO_SCALAR_MEMREF_LOAD_SUPPORT_INTRODUCED=YES
// CHECK: NONTRANSPOSED_V_GATHER_REMAINS_STAGED=YES
// CHECK: NATURAL_EXP_SOFTMAX_SEMANTICS_PRESERVED=YES
// CHECK: NO_SOURCE_NAME_PATH_FIXTURE_SPECIAL_CASES=YES
// CHECK: QK_SCORE_GENERATION_REMAINS_STAGED=YES
// CHECK: DOT_CONTRACT_REMAINS_STAGED=YES
// CHECK: READY_FOR_TRITON=NO
