// RUN: python3 %vc4_repo_root/compiler/test/Conversion/VC4ValueToVC4Kernel/Support/audit_phase14_value_storage_numeric_static.py --repo-root %vc4_repo_root | FileCheck %s

// CHECK: PHASE14_VALUE_STORAGE_NUMERIC_SOURCE_AUDIT=PASS
// CHECK: F16_STORAGE_CONVERSIONS_USE_CENTRAL_HELPERS=YES
// CHECK: F16_STORE_REQUIRES_FINITE_POLICY=YES
// CHECK: NATIVE_F16_ARITHMETIC_STAGED=YES
// CHECK: BF16_FP8_STAGED=YES
// CHECK: INT8_INT16_QUANTIZED_STORAGE_STAGED=YES
// CHECK: FP_TO_INT_CAST_STAGED=YES
// CHECK: I32_TO_F32_CAST_STATUS=STAGED_BY_LOWER_HALF_GAP
// CHECK: NO_FIXTURE_NAME_OR_PATH_SPECIAL_CASES=YES
// CHECK: NO_HIDDEN_EXACT_ROUNDING_CLAIM=YES
// CHECK: READY_FOR_TRITON=NO
