// RUN: python3 %vc4_repo_root/compiler/test/Conversion/VC4ValueToVC4Kernel/Support/audit_phase8_value_cf.py --repo-root %vc4_repo_root | FileCheck %s

// CHECK: PHASE8_VALUE_CF_AUDIT=PASS
// CHECK: DIRECT_VALUE_TO_LOWER_HALF=NO
// CHECK: DIRECT_TTIR_TO_VC4KERNEL=NO
// CHECK: RAW_SCF_IN_VC4KERNEL_POLICY=NO
// CHECK: PRODUCER_DIALECTS_IN_VC4KERNEL_POLICY=NO
// CHECK: FIXTURE_NAME_SPECIAL_CASES=NO
// CHECK: CUSTOM_SCF_TO_CF_LOWERING=NO
// CHECK: VC4VALUE_CONTROL_FLOW_OPS=NO
// CHECK: BRANCH_SEMANTICS_COMMENTS_ONLY=NO
// CHECK: READY_FOR_TRITON=NO
